version: 2 
jobs: 
  build:
    
    working_directory: ~/meterian-plugin 

    docker: 
      - image: circleci/openjdk:8-jdk-browsers 

    steps: 

      - checkout 

      - restore_cache: 
          key: meterian-plugin-{{ checksum "pom.xml" }}
      
      - run: mvn dependency:go-offline 
      
      - save_cache: 
          paths:
            - ~/.m2
          key: meterian-plugin-{{ checksum "pom.xml" }}
      
      - run: mvn package 
      
      - store_test_results: 
          path: target/surefire-reports
      
